### ISSUE TITLE
Add online dsprotection rejection mechanism

### ISSUE THREAD

**Issue by this-kramer** [cryptimeleon/incentive-system#155]
Scenario:
 - User sends spend-request
 - Incentive service asks dsp-service if the dsid of the request was used before (O(1) lookup)
 - Reject request if found
 - Otherwise continue as before and run dbsync afterward

=> Benefit: precaution instead of cleaning up after a ds-attack where possible; does not record double-spends that happen in the same store

**Comment by pschuermann97** [comment]
current state: Paul made buffering mechanism yesterday, Patrick now needs to implement check-and-reject mechanism
