### ISSUE TITLE
Wrong token count after cascadingInvalidationsTest of double-spending protection service

### ISSUE THREAD

**Issue by pschuermann97** [cryptimeleon/incentive-system#75]
The mentioned test attempts to construct the graph from Chapter 6 of the 2019 UACS paper.
Thus the expected token count would be 5, actual is 4.

Log output from the test shows that the program thinks that the remainder token dsid5 of transaction t2Prime is already in the database so it does not add it.
Since dsid5 never is computed before (since it is a remainder token which are only traced upon double-spending attempts being detected), it is most likely that this is the missing token.

**Comment by JanBobolz** [comment]
The issue seems to be that dsid3 == dsid5, because t2 and t2' both use exactly the same inputs and we've derandomized all the protocols so much that this leads to t2 und t2' both producing the same remainder token dsid. In short, we're basically running t2 and t2' in "recovery" mode, i.e. we're pretending this is a valid second attempt at spending (but it's not, because they have different transaction ids).

Interestingly, this is an issue in the paper 🙈. What _should_ happen is that the provider chooses a different eskProvStar for t2 and t2'. 
![Image on 2022-03-21 01 11 15 PM](https://user-images.githubusercontent.com/6500790/159258830-f9203aca-c790-4ae6-9d2f-01ea3657bc39.jpg)
So that evaluation of the PRF should take the same input as H when computing gamma, i.e. `PRF(k, dsid, tid, Cpre)` (or, equivalently, `PRF(gamma)`)

**Comment by this-kramer** [comment]
@pschuermann97 can we close this issue as resolved?

**Comment by pschuermann97** [comment]
@JanBobolz 
The definition of Spend-Deduct in the paper is outdated with respect to our implementation since we do not have anything like the spend amount anymore. Is it fine to just use dsid and tid to make the esk_prov unique for each transaction using a fixed token (i.e. double-spending)? My feeling says yes.

**Comment by pschuermann97** [comment]
Implemented it like this, will open PR now. Feel free to complain if I overlooked something ^^

**Comment by JanBobolz** [comment]
In place of `k` within the computation of `gamma` and `esk_prov`, we would use the public user choice (@this-kramer probably knows its real name. The thing that tells the store whether the user is currently redeeming a teddy bear or a frying pan).

**Comment by JanBobolz** [comment]
If we omit this, the user will get the same challenge when attempting to first retrieve a teddy bear and then again (with the same token and same randomness) the frying pan. 

Probably this can also be prevented by fixing the basket content after the first try, but why take the risk?

**Comment by this-kramer** [comment]
> In place of `k` within the computation of `gamma` and `esk_prov`, we would use the public user choice (@this-kramer probably knows its real name. The thing that tells the store whether the user is currently redeeming a teddy bear or a frying pan).

This represents the json object sent to the server, + the basketId:
https://github.com/cryptimeleon/incentive-system/blob/develop/services/client/src/main/java/org/cryptimeleon/incentive/client/dto/inc/SpendRequestDto.java

**Comment by pschuermann97** [comment]
@this-kramer what would be the best way to access this SpendRequestDto from the IncentiveSystem.generateSpendRequestResponse context? The dto does not seem to be passed right now when calling this method.

**Comment by pschuermann97** [comment]
The longer I think about this, the weirder it seems to me - a Dto in crypto? Crypto should not care about Dtos and stuff but only about pure math, at least that is what I thought.

**Comment by this-kramer** [comment]
> @this-kramer what would be the best way to access this SpendRequestDto from the IncentiveSystem.generateSpendRequestResponse context? The dto does not seem to be passed right now when calling this method.

I would suggest to abstract it to some extent (e.g. a string, or some interface that admits hashing) from which we can compute gamma and eskprov. For the implementation in crypto, it is not important to know which data format the associated data has.
Can you sketch more precisely for which functionality you need the dto in crypto?

The dsprotection service however has access to this dto, so I would think of a translating it there from dto -> whatever crypto expects.

**Comment by this-kramer** [comment]
> The longer I think about this, the weirder it seems to me - a Dto in crypto? Crypto should not care about Dtos and stuff but only about pure math, at least that is what I thought.
> 
> How about hashing the Dto to Zn and including this number c (for claim) in the spend request (c is generated outside crypto, i.e. maybe somewhere in the app context).

I think the hash solution is the way to go, but I would not trust user inputs and hence move it to the dsprotection service.
Further, to be a little more flexible, lets define an intermediate representation of the data and make that intermediate data class `UniqueByteRepresentable`. The algorithm you referred to could expect a `c` of that type.

IMO, an intermediate representation makes testing and prototyping easier, and helps with later changes. We need to include the basketId anyway, hence the dto is not 100% suitable right now.

**Comment by pschuermann97** [comment]
I think that c must be generated in the app since the flow is
1. user initiates spend transaction
2. provider runs Deduct (this is where c is needed, see above paper excerpt)
3. provider sends stuff to dsprotectionservice

**Comment by pschuermann97** [comment]
Its not about computing gamma btw.
It is about computing some userChoiceID that identifies the choice of rewards the user has made.

**Comment by pschuermann97** [comment]
> If we omit this, the user will get the same challenge when attempting to first retrieve a teddy bear and then again (with the same token and same randomness) the frying pan. Hence this would not be detected as double spending.
> 
> Probably this can also be prevented by fixing the basket content after the first try and hence disabling the ability to then ask for the frying pan - somehow, but why take the risk?

Wait maybe it is also about computing gamma.

Shouldn't this userChoice ID be part of the computation of gamma as well then?

**Comment by pschuermann97** [comment]
Suggestion for userChoiceID by @this-kramer : putting together basketID and ID of the ZKP that the user wants to perform.

@this-kramer 
However isn't the basket mutable? So wouldn't this require freezing the basket content upon making a spend request, right?

**Comment by JanBobolz** [comment]
> Wait maybe it is also about computing gamma.
> 
> Shouldn't this userChoice ID be part of the computation of gamma as well then?

https://github.com/cryptimeleon/incentive-system/issues/75#issuecomment-1105078230

**Comment by pschuermann97** [comment]
Token count is correct now, added dsid, tid and userChoice to the preimage that is used to compute esk_prov,
also added userChoice to the computation of gamma.

However, userChoice is not yet what it is supposed to be (used some ZnElement, more precisely the tid, to get the code compiling). The user choice is something that should be computable from the basket ID and the reward item contained in the basket.

Since the token count is fixed now, I will close this issue. The user choice problem is still marked as left-open (issue #103).
