### ISSUE TITLE
Doublespending Service Integration

### ISSUE THREAD

**Issue by this-kramer** [cryptimeleon/incentive-system#97]
We need to integrate the doublespending service to the existing infrastructure. This includes:

- [x] #67 
- [x] #88 
- [x] Adding it to the deployment
- [x] Sending results of the Spend protocol either directly or in bulk to the DS service

**Comment by this-kramer** [comment]
first part: #122

**Comment by pschuermann97** [comment]
according to above checklist this issue is closed now, integration of incentive and dsprotection service not tested yet
